"""Resource Registry — a managed index of the host CTF-tools repository.

`RESOURCE_MAP.json` maps resource names (skills, scripts, tools, bin entries,
notes) to their path, category, invoke template, and required platform. The map
is generated by `scripts/generate_resource_map.py` and validated lazily at
lookup time. A missing resource is a hard BLOCKER, never a silent fallback.
"""

from __future__ import annotations

import json
import os
import shutil
from functools import lru_cache
from pathlib import Path
from typing import Any, Optional

REPO_ROOT = Path(__file__).resolve().parent.parent
RESOURCE_MAP_PATH = Path(
    os.getenv("DUACHUOT_RESOURCE_MAP", REPO_ROOT / "resources" / "RESOURCE_MAP.json")
)

CATEGORIES = ("skill", "script", "tool", "bin", "note")


def default_root() -> Path:
    return Path(os.getenv("CTF_TOOLS_DIR", Path.home() / "ctf-tools"))


def discover_resources(root: Path) -> list[dict[str, Any]]:
    """Scan a ctf-tools repository and return resource entries."""
    root = root.resolve()
    entries: list[dict[str, Any]] = []

    def add(name: str, category: str, path: Path) -> None:
        entries.append(
            {
                "name": name,
                "category": category,
                "path": str(path),
                "invoke": _invoke_template(path),
                "platform": "any",
            }
        )

    skills = root / "skills"
    if skills.is_dir():
        for skill_dir in sorted(p for p in skills.iterdir() if p.is_dir()):
            add(skill_dir.name, "skill", skill_dir / "SKILL.md")
            scripts = skill_dir / "scripts"
            if scripts.is_dir():
                for script in sorted(s for s in scripts.iterdir() if s.is_file()):
                    if script.suffix in {".py", ".sh"} or script.stat().st_mode & 0o111:
                        add(f"{skill_dir.name}/{script.name}", "script", script)

    tools = root / "tools"
    if tools.is_dir():
        for tool_dir in sorted(p for p in tools.iterdir() if p.is_dir()):
            add(tool_dir.name, "tool", tool_dir)

    bins = root / "bin"
    if bins.is_dir():
        for entry in sorted(p for p in bins.iterdir() if p.is_file()):
            add(entry.name, "bin", entry)

    notes = root / "notes"
    if notes.is_dir():
        for note in sorted(p for p in notes.iterdir() if p.suffix == ".md"):
            add(note.stem, "note", note)

    return entries


def _invoke_template(path: Path) -> str:
    suffix = path.suffix
    if suffix == ".py":
        return f"python {path}"
    if suffix == ".sh":
        return f"bash {path}"
    if suffix == ".md":
        return f"read {path}"
    return str(path)


@lru_cache(maxsize=8)
def load_resource_map(path: Path) -> dict[str, Any]:
    """Load and validate RESOURCE_MAP.json. Raises FileNotFoundError if missing."""
    with open(path, "r", encoding="utf-8") as handle:
        raw = json.load(handle)
    _validate_map(raw)
    return raw


def reset_resource_map_cache() -> None:
    load_resource_map.cache_clear()


def _validate_map(raw: dict[str, Any]) -> None:
    if not isinstance(raw, dict) or "version" not in raw or "resources" not in raw:
        raise ValueError("RESOURCE_MAP.json must contain 'version' and 'resources'")
    if not isinstance(raw["resources"], dict):
        raise ValueError("RESOURCE_MAP.json 'resources' must be an object keyed by name")


def resolve_resource(
    name: str,
    *,
    refresh: bool = False,
    map_path: Optional[Path] = None,
) -> dict[str, Any]:
    """Resolve a resource by name. Returns availability evidence.

    Raises LookupError when the name is unknown, and returns
    available=False (with reason) when the mapped path is not usable.
    """
    if refresh:
        reset_resource_map_cache()
    path = Path(map_path) if map_path else RESOURCE_MAP_PATH
    data = load_resource_map(path)
    resources = data["resources"]
    if name not in resources:
        raise LookupError(
            f"resource '{name}' is not in RESOURCE_MAP.json; "
            f"known categories: {', '.join(CATEGORIES)}"
        )
    entry = dict(resources[name])
    entry["name"] = name
    path = Path(entry["path"])
    entry["available"] = path.exists()
    if not entry["available"]:
        entry["reason"] = (
            f"resource path does not exist: {path} (BLOCKER — do not run the wrong tool)"
        )
    else:
        invoke_tool = entry.get("invoke", "").split()[:1]
        if invoke_tool and invoke_tool[0] not in {"python", "bash", "read"}:
            if not shutil.which(invoke_tool[0]):
                entry["available"] = False
                entry["reason"] = f"invoke binary '{invoke_tool[0]}' not found in PATH (BLOCKER)"
    return entry


def all_resources(
    *, refresh: bool = False, map_path: Optional[Path] = None
) -> list[dict[str, Any]]:
    path = Path(map_path) if map_path else RESOURCE_MAP_PATH
    if refresh:
        reset_resource_map_cache()
    data = load_resource_map(path)
    return [resolve_resource(name, map_path=path) for name in sorted(data["resources"])]


def generate_resource_map(root: Path) -> dict[str, Any]:
    """Build the full map document from a ctf-tools repository root."""
    resources = {entry["name"]: entry for entry in discover_resources(root)}
    return {
        "version": 1,
        "generated_by": "scripts/generate_resource_map.py",
        "root": str(Path(root).resolve()),
        "resources": dict(sorted(resources.items())),
    }


__all__ = [
    "RESOURCE_MAP_PATH",
    "CATEGORIES",
    "default_root",
    "discover_resources",
    "load_resource_map",
    "reset_resource_map_cache",
    "resolve_resource",
    "all_resources",
    "generate_resource_map",
]
